module.exports = [{"matricula":1,"nome":"Jackie Kaaskooper","ramal":12,"email":"jkaaskooper0@unesco.org","setor":"tecnologia","dtNascimento":"23/12/2002"},
{"matricula":2,"nome":"Foster Walczynski","ramal":16,"email":"fwalczynski1@youtu.be","setor":"financeiro","dtNascimento":"29/01/1990"},
{"matricula":3,"nome":"Heda Bariball","ramal":24,"email":"hbariball2@china.com.cn","setor":"saude","dtNascimento":"12/01/1991"},
{"matricula":4,"nome":"Wadsworth Giacovazzo","ramal":14,"email":"wgiacovazzo3@wufoo.com","setor":"vendas","dtNascimento":"15/02/1993"},
{"matricula":5,"nome":"Cirilo Dewfall","ramal":11,"email":"cdewfall4@topsy.com","setor":"Jurídico","dtNascimento":"24/12/2000"},
{"matricula":6,"nome":"Ulises Castellani","ramal":15,"email":"ucastellani5@japanpost.jp","setor":"vendas","dtNascimento":"16/11/1992"},
{"matricula":7,"nome":"Melosa Skeene","ramal":17,"email":"mskeene6@google.es","setor":"Jurídico","dtNascimento":"13/10/1992"},
{"matricula":8,"nome":"Natka Goldsworthy","ramal":18,"email":"ngoldsworthy7@who.int","setor":"saude","dtNascimento":"28/08/2001"},
{"matricula":9,"nome":"Sherline Chateau","ramal":20,"email":"schateau8@google.com.au","setor":"saude","dtNascimento":"13/06/1996"},
{"matricula":10,"nome":"Neddie Rowling","ramal":19,"email":"nrowling9@fda.gov","setor":"vendas","dtNascimento":"23/04/1999"},
{"matricula":11,"nome":"Ryon Semechik","ramal":21,"email":"rsemechika@bigcartel.com","setor":"tecnologia","dtNascimento":"07/07/1997"},
{"matricula":12,"nome":"Ailee Mascall","ramal":22,"email":"amascallb@youku.com","setor":"sac","dtNascimento":"10/05/2001"},
{"matricula":13,"nome":"Nicholas Pegden","ramal":23,"email":"npegdenc@theguardian.com","setor":"vendas","dtNascimento":"15/03/2002"},
{"matricula":14,"nome":"Ely Vanetti","ramal":13,"email":"evanettid@nyu.edu","setor":"vendas","dtNascimento":"13/02/1995"},
{"matricula":15,"nome":"Chrissy Shave","ramal":25,"email":"cshavee@apple.com","setor":"tecnologia","dtNascimento":"31/01/2000"}];